general_content:
    resource: "@GeneralContentBundle/Resources/config/routing.yml"
    prefix:   /

mensaje:
    resource: "@MensajeBundle/Resources/config/routing.yml"
    prefix:   /mensaje/

pais:
    resource: "@PaisBundle/Resources/config/routing.yml"
    prefix:   /pais/

usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /usuario/

